import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";
import 'animate.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F0F2F5]`}>
        <Toaster />
        <Header />
        <div className="flex h-screen overflow-hidden p-3.5 lg:p-8 mt-24">
          <Sidebar />
          <div className="relative flex flex-1 flex-col overflow-y-auto overflow">
            <main className="md:px-8">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
